### ISSUE TITLE
Spring Boot Swagger Authorization Code grant

### ISSUE THREAD

**Issue by anj-kr** [hendisantika/springboot-oauth2-jwt-swagger-ui#1]
Thanks for the example. But I would like to understand using spring boot and the swagger latest version (Swagger UI v. 3.38.0) if the application is configured using authorization code flow and when the user hit the application in the browser before loading of swagger UI , is it possible to complete the authorization code process without any action from the user.

Basically, I'm looking for an OpenID Connect Discovery example with swagger and spring boot. Thank you!

**Comment by hendisantika** [comment]
Consider to use https://springdoc.org/.

**Comment by anj-kr** [comment]
Thank you for the response. Do you have an example with OpenId connect which uses an authorization code for swagger? If not, then I will check further.

**Comment by hendisantika** [comment]
No, I don't have that.

If You success let me know.

**Comment by anj-kr** [comment]
Sure. Thank you !

**Comment by anj-kr** [comment]
Just to update -Still looking for example. May I know is it possible to hide the client id,secret , redirect URI from swagger URL. Right now when clicked on Authorize button in swagger UI , it is displaying the values which need to be hidden using config.

**Comment by anj-kr** [comment]
just want to check. Are you able to achieve this using springdoc

**Comment by hendisantika** [comment]
I have not tried it @anj-kr ...

Can You do that? Send PR to me

**Comment by anj-kr** [comment]
Ok. Let me check that. Thanks
